import { useWhisper } from "@chengsokdara/use-whisper";
import { type NextPage } from "next";
import Head from "next/head";
import { useRef, useState } from "react";
import { Microphone } from "icons";

const Home: NextPage = () => {
  const {
    transcript,
    transcribing,
    recording,
    speaking,
    pauseRecording,
    startRecording,
    stopRecording,
  } = useWhisper({
    apiKey: "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",
    streaming: true,
    timeSlice: 1_000,
    whisperConfig: {
      language: "en",
    },
  });

  return (
    <>
      <Head>
        <title>VNAI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <div className="bg-red-500 text-center">header</div>
        <div className="mt-20 flex flex-col items-center gap-5">
          <p className="text-3xl font-bold">
            Transform jumbled ideas into crystal-clear text effortlessly
          </p>
          <button
            onClick={() => startRecording()}
            className="flex h-20 w-20 items-center justify-center rounded-full border border-[#D0D5E6]"
          >
            <Microphone className="h-16 w-16" />
          </button>
          <p>Recording: {recording}</p>
          <p>Speaking: {speaking}</p>
          <p>Transcribing: {transcribing}</p>

          <button onClick={() => pauseRecording()}>Pause</button>
          <button onClick={() => stopRecording()}>Stop</button>
          <p>{transcript.text}</p>
        </div>
      </main>
    </>
  );
};

export default Home;
