"use client";

import { useWhisper } from "@chengsokdara/use-whisper";
import Head from "next/head";
import { type FC, useEffect, useState } from "react";
import { Microphone } from "icons";
import { Button } from "@/components/ui/button";
import Card from "@/components/ui/card";

const Page: FC = () => {
  const [transcribedText, setTranscribedText] = useState(
    "I'm always thinking about implementing user interactions and transcriptions so I'm always looking for a new behavior in. So thank you so much for your help. This is Monica Ndio."
  );

  const {
    transcript,
    transcribing,
    pauseRecording,
    startRecording,
    stopRecording,
  } = useWhisper({
    apiKey: "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",
    streaming: true,
    timeSlice: 1_000,
    whisperConfig: {
      language: "en",
    },
  });

  const generateSummarizedText = async (e: any) => {
    e.preventDefault();

    const response = await fetch("/api/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        text: transcribedText,
      }),
    });

    const answer = await response.json();
    console.log(answer);
    return answer;
  };

  useEffect(() => {
    if (transcribing === false)
      if (transcript.text) setTranscribedText(transcript.text);
  }, [transcribing]);

  console.log(transcribing);
  console.log(transcribedText);
  return (
    <>
      <Head>
        <title>VNAI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-24 my-8 flex min-h-screen flex-col">
        <div className="mt-20 flex flex-col items-center gap-5">
          <p className="-z-10 text-3xl font-bold">
            Transform jumbled ideas into crystal-clear text effortlessly
          </p>
          <button
            onClick={() => startRecording()}
            className="flex h-20 w-20 items-center justify-center rounded-full border border-[#D0D5E6]"
          >
            <Microphone className="h-16 w-16" />
          </button>
          <Button variant="secondary" onClick={generateSummarizedText}>
            Summarize
          </Button>
          <button onClick={() => pauseRecording()}>Pause</button>
          <button onClick={() => stopRecording()}>Stop</button>
          <p>{transcript.text}</p>
        </div>
        <section className="mt-24 flex flex-col items-center">
          <h1 className="text-3xl font-semibold">Your Notes</h1>
          <div className="flex flex-wrap justify-center gap-5 py-12">
            <Card
              title="High School"
              content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere nemo
        laborum eius, quibusdam veritatis nihil doloribus facilis voluptates,
        voluptas architecto mollitia? Optio, aliquid animi distinctio qui beatae
        nostrum deserunt cum?"
            />
          </div>
        </section>
      </main>
    </>
  );
};

export default Page;
